---
- hosts: all
  tasks:
    - name: install ssm agent
      become: yes
      become_user: root
      yum:
        name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
        state: present

      # should be a handler, but this is just a test
    - name: Starting SSM service    
      service:     
        name: amazon-ssm-agent     
        enabled: yes     
        state: started
